# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customers.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_customers(object):
    def setupUi(self, customers):
        customers.setObjectName("customers")
        customers.resize(500, 280)
        customers.setStyleSheet("background-color: #7393ad;")
        self.centralwidget = QtWidgets.QWidget(customers)
        self.centralwidget.setObjectName("centralwidget")
        self.DB_custome_name_value = QtWidgets.QLineEdit(self.centralwidget)
        self.DB_custome_name_value.setGeometry(QtCore.QRect(170, 80, 320, 30))
        self.DB_custome_name_value.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color:#8BE8E5;\n"
"    color: rgb(202, 8, 255);\n"
"    border: 1px  rgb(237, 255, 152);\n"
"border-radius: 5px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(2, 35, 255);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(0, 255, 162);\n"
"}")
        self.DB_custome_name_value.setObjectName("DB_custome_name_value")
        self.new_customer_label = QtWidgets.QLabel(self.centralwidget)
        self.new_customer_label.setGeometry(QtCore.QRect(180, 10, 120, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.new_customer_label.setFont(font)
        self.new_customer_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color:rgb(255, 255, 255);")
        self.new_customer_label.setObjectName("new_customer_label")
        self.DB_custome_name_label = QtWidgets.QLabel(self.centralwidget)
        self.DB_custome_name_label.setGeometry(QtCore.QRect(10, 45, 110, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.DB_custome_name_label.setFont(font)
        self.DB_custome_name_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color:rgb(255, 255, 255);")
        self.DB_custome_name_label.setObjectName("DB_custome_name_label")
        self.Document_custome_name_label = QtWidgets.QLabel(self.centralwidget)
        self.Document_custome_name_label.setGeometry(QtCore.QRect(10, 85, 160, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.Document_custome_name_label.setFont(font)
        self.Document_custome_name_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color:rgb(255, 255, 255);")
        self.Document_custome_name_label.setObjectName("Document_custome_name_label")
        self.new_Button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.new_Button_2.setGeometry(QtCore.QRect(10, 120, 220, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.new_Button_2.setFont(font)
        self.new_Button_2.setStyleSheet("QPushButton {\n"
"background: #312E63;\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(48, 221, 255);\n"
"}")
        self.new_Button_2.setObjectName("new_Button_2")
        self.new_Button = QtWidgets.QPushButton(self.centralwidget)
        self.new_Button.setGeometry(QtCore.QRect(270, 120, 220, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.new_Button.setFont(font)
        self.new_Button.setStyleSheet("QPushButton {\n"
"background-color: #6F61C0;\n"
"color:white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(48, 221, 255);\n"
"}")
        self.new_Button.setObjectName("new_Button")
        self.DB_custome_short_name_value = QtWidgets.QLineEdit(self.centralwidget)
        self.DB_custome_short_name_value.setGeometry(QtCore.QRect(170, 40, 320, 30))
        self.DB_custome_short_name_value.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color:#8BE8E5;\n"
"    color: rgb(202, 8, 255);\n"
"    border: 1px  rgb(237, 255, 152);\n"
"border-radius: 5px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(2, 35, 255);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(0, 255, 162);\n"
"}")
        self.DB_custome_short_name_value.setObjectName("DB_custome_short_name_value")
        self.update_customer_label = QtWidgets.QLabel(self.centralwidget)
        self.update_customer_label.setGeometry(QtCore.QRect(160, 170, 191, 25))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(16)
        self.update_customer_label.setFont(font)
        self.update_customer_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color:rgb(255, 255, 255);")
        self.update_customer_label.setObjectName("update_customer_label")
        self.update_Button = QtWidgets.QPushButton(self.centralwidget)
        self.update_Button.setGeometry(QtCore.QRect(330, 200, 160, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.update_Button.setFont(font)
        self.update_Button.setStyleSheet("QPushButton {\n"
"background-color: #6F61C0;\n"
"color:white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(48, 221, 255);\n"
"}")
        self.update_Button.setObjectName("update_Button")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 200, 300, 30))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    background-color:#8BE8E5;\n"
"    color: rgb(199, 55, 255);\n"
"    border: 1px  rgb(237, 255, 152);\n"
"border-radius: 5px;\n"
"}\n"
"QComboBox:hover {\n"
"    border: 3px solid rgb(2, 35, 255);\n"
"}\n"
"QComboBox:focus {\n"
"\n"
"    border: 3px solid rgb(0, 255, 162);\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.delete_Button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_Button.setGeometry(QtCore.QRect(330, 240, 160, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.delete_Button.setFont(font)
        self.delete_Button.setStyleSheet("QPushButton {\n"
"background: #312E63;\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(48, 221, 255);\n"
"}")
        self.delete_Button.setObjectName("delete_Button")
        customers.setCentralWidget(self.centralwidget)

        self.retranslateUi(customers)
        QtCore.QMetaObject.connectSlotsByName(customers)

    def retranslateUi(self, customers):
        _translate = QtCore.QCoreApplication.translate
        customers.setWindowTitle(_translate("customers", "MainWindow"))
        self.new_customer_label.setText(_translate("customers", "Нова компанія"))
        self.DB_custome_name_label.setText(_translate("customers", "Назва у базі"))
        self.Document_custome_name_label.setText(_translate("customers", "Назва у документі"))
        self.new_Button_2.setText(_translate("customers", "Скинути"))
        self.new_Button.setText(_translate("customers", "Додати"))
        self.update_customer_label.setText(_translate("customers", "Редагувати компанію"))
        self.update_Button.setText(_translate("customers", "Редагувати"))
        self.delete_Button.setText(_translate("customers", "Видалити"))
