# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BendingPriceCalc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import style

from PyQt5 import QtCore, QtGui, QtWidgets

type_holder_list = [
    "Оберіть тип кріплення",
    "Amada-promecam",
    "Trumpf-Wila",
    "Bystronic"
]

item_list_amada = [
    "Пуансон",
    "Матриця одноручова",
    "Пуансон плющення",
    "Матриця плющення",
    "Матриця багаторучова",
    "Тримач пуансона",
    "Прижимні планки",
    "Тримач матриці"
]

item_list_trumpf_wila = [
    "Пуансон",
    "Матриця",
    "Пуансон плющення",
    "Матриця плющення",
    "Кнопка",
    "Штифт"
]

category = {
    type_holder_list[0]: type_holder_list[0],
    type_holder_list[1]: item_list_amada,
    type_holder_list[2]: item_list_trumpf_wila,
    type_holder_list[3]: item_list_trumpf_wila[0:4],
}


week_day = {
    1: "понеділок",
    2: "вівторок",
    3: "середа",
    4: "четвер",
    5: "п'ятниця",
    6: "субота",
    7: "неділя"
}

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(820, 880)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle("BendingPriceCalc")
        MainWindow.setStyleSheet("/*background-color: qlineargradient(spread:pad, x1:0.011, y1:0.852455, x2:0.96, y2:0.085, stop:0 rgba(112, 2, 117, 255), stop:1 rgba(128, 16, 255, 255));*/\n"
"background-color:rgb(30, 0, 65);")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.bending_price_calc_window = QtWidgets.QWidget(MainWindow)
        self.bending_price_calc_window.setStyleSheet("")
        self.bending_price_calc_window.setObjectName("bending_price_calc_window")
        self.company_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.company_label.setGeometry(QtCore.QRect(20, 20, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.company_label.setFont(font)
        self.company_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color:rgb(190, 227, 255);")
        self.company_label.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.company_label.setAlignment(QtCore.Qt.AlignCenter)
        self.company_label.setObjectName("company_label")
        self.company_name = QtWidgets.QLineEdit(self.bending_price_calc_window)
        self.company_name.setGeometry(QtCore.QRect(130, 20, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.company_name.setFont(font)
        self.company_name.setStyleSheet("QLineEdit{\n"
"    background-color:rgb(190, 227, 255);\n"
"    color: rgb(0, 0, 100);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(2, 35, 255);\n"
"}\n"
"QLineEdit:focus {\n"
"\n"
"    border: 3px solid rgb(225, 255, 249);\n"
"}")
        self.company_name.setAlignment(QtCore.Qt.AlignCenter)
        self.company_name.setObjectName("company_name")
        self.type_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.type_label.setGeometry(QtCore.QRect(20, 60, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.type_label.setFont(font)
        self.type_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(190, 227, 255);")
        self.type_label.setAlignment(QtCore.Qt.AlignCenter)
        self.type_label.setObjectName("type_label")
        self.type_value = QtWidgets.QComboBox(self.bending_price_calc_window)
        self.type_value.setGeometry(QtCore.QRect(130, 60, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.type_value.setFont(font)
        self.type_value.setStyleSheet("QComboBox{\n"
"    background-color:rgb(190, 227, 255);\n"
"    color:  rgb(0, 0, 100);\n"
"    border: 1px  rgb(237, 255, 152);\n"
"border-radius: 5px;\n"
"}\n"
"QListView{\n"
"    background-color:rgb(190, 227, 255);\n"
"}\n"
"QScrollBar{\n"
"    background-color:rgb(190, 227, 255);\n"
"}\n"
"QComboBox:hover {\n"
"    border: 3px solid rgb(2, 35, 255);\n"
"}\n"
"QComboBox:focus {\n"
"\n"
"    border: 3px solid rgb(0, 255, 162);\n"
"}\n"
"QScrollBar {\n"
"    background-color: rgb(237, 255, 152);\n"
"    color: yellow;\n"
"}\n"
"QScrollBar::handle::pressed {\n"
"    background : lightgreen;\n"
"}")
        self.type_value.setObjectName("type_value")
        self.item_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.item_label.setGeometry(QtCore.QRect(20, 100, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.item_label.setFont(font)
        self.item_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(190, 227, 255);")
        self.item_label.setAlignment(QtCore.Qt.AlignCenter)
        self.item_label.setObjectName("item_label")
        self.item_value = QtWidgets.QComboBox(self.bending_price_calc_window)
        self.item_value.setGeometry(QtCore.QRect(130, 100, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.item_value.setFont(font)
        self.item_value.setStyleSheet("QComboBox{\n"
"    background-color: rgb(190, 227, 255);\n"
"    color:  rgb(0, 0, 100);\n"
"    border: 1px  rgb(237, 255, 152);\n"
"border-radius: 5px;\n"
"}\n"
"QComboBox:hover {\n"
"    border: 3px solid rgb(2, 35, 255);\n"
"}\n"
"QComboBox:focus {\n"
"\n"
"    border: 3px solid rgb(0, 255, 162);\n"
"}")
        self.item_value.setObjectName("item_value")
        self.number_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.number_label.setGeometry(QtCore.QRect(20, 140, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.number_label.setFont(font)
        self.number_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(190, 227, 255);")
        self.number_label.setAlignment(QtCore.Qt.AlignCenter)
        self.number_label.setObjectName("number_label")
        self.number_value = QtWidgets.QComboBox(self.bending_price_calc_window)
        self.number_value.setGeometry(QtCore.QRect(130, 140, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.number_value.setFont(font)
        self.number_value.setStyleSheet("QComboBox{\n"
"    background-color: rgb(190, 227, 255);\n"
"    color:  rgb(0, 0, 100);\n"
"    border: 1px  rgb(237, 255, 152);\n"
"border-radius: 5px;\n"
"}\n"
"QComboBox:hover {\n"
"    border: 3px solid rgb(2, 35, 255);\n"
"}\n"
"QComboBox:focus {\n"
"    border: 3px solid rgb(0, 255, 162);\n"
"}")
        self.number_value.setObjectName("number_value")
        self.length_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.length_label.setGeometry(QtCore.QRect(20, 180, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.length_label.setFont(font)
        self.length_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(190, 227, 255);")
        self.length_label.setAlignment(QtCore.Qt.AlignCenter)
        self.length_label.setObjectName("length_label")
        self.length_value = QtWidgets.QComboBox(self.bending_price_calc_window)
        self.length_value.setGeometry(QtCore.QRect(130, 180, 430, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.length_value.setFont(font)
        self.length_value.setStyleSheet("QComboBox{\n"
"    background-color: rgb(190, 227, 255);\n"
"    color:   rgb(0, 0, 100);\n"
"    border: 1px  rgb(237, 255, 152);\n"
"border-radius: 5px;\n"
"}\n"
"QComboBox:hover {\n"
"    border: 3px solid rgb(2, 35, 255);\n"
"}\n"
"QComboBox:focus {\n"
"\n"
"    border: 3px solid rgb(0, 255, 162);\n"
"}")
        self.length_value.setObjectName("length_value")
        self.quantity_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.quantity_label.setGeometry(QtCore.QRect(20, 220, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.quantity_label.setFont(font)
        self.quantity_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(190, 227, 255);")
        self.quantity_label.setObjectName("quantity_label")
        self.quantity_value = QtWidgets.QSpinBox(self.bending_price_calc_window)
        self.quantity_value.setGeometry(QtCore.QRect(130, 220, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.quantity_value.setFont(font)
        self.quantity_value.setStyleSheet("QSpinBox{\n"
"    background-color: rgb(190, 227, 255);\n"
"    color:  rgb(0, 0, 100);\n"
"border-radius: 5px;\n"
"}\n"
"QSpinBox:hover {\n"
"    border: 3px solid rgb(2, 35, 255);\n"
"}\n"
"QSpinBox:focus {\n"
"\n"
"    border: 3px solid rgb(0, 255, 162);\n"
"}\n"
"QSpinBox::up-arrow {\n"
"color : blue;\n"
"}\n"
"QSpinBox::down-arrow {\n"
"color : red;\n"
"}\n"
"\n"
"")
        self.quantity_value.setAlignment(QtCore.Qt.AlignCenter)
        self.quantity_value.setObjectName("quantity_value")
        self.add_item_button = QtWidgets.QPushButton(self.bending_price_calc_window)
        self.add_item_button.setGeometry(QtCore.QRect(10, 260, 230, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.add_item_button.setFont(font)
        self.add_item_button.setStyleSheet("QPushButton {\n"
"color:white;\n"
"/*background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(102, 158, 255, 255), stop:0.55 rgba(71, 61, 235, 255), stop:0.98 rgba(27, 2, 212, 255), stop:1 rgba(0, 0, 0, 0)); */\n"
"background-color: rgb(102, 161, 255);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  rgb(48, 221, 255);\n"
"}")
        self.add_item_button.setObjectName("add_item_button")
        self.reset_button = QtWidgets.QPushButton(self.bending_price_calc_window)
        self.reset_button.setEnabled(True)
        self.reset_button.setGeometry(QtCore.QRect(330, 260, 230, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.reset_button.setFont(font)
        self.reset_button.setStyleSheet("QPushButton {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 102, 102, 255), stop:0.5625 rgba(194, 80, 21, 255), stop:0.98 rgba(196, 4, 56, 255), stop:1 rgba(0, 0, 0, 0));\n"
"color:white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  rgb(48, 221, 255);\n"
"}")
        self.reset_button.setObjectName("reset_button")
        self.table = QtWidgets.QTableWidget(self.bending_price_calc_window)
        self.table.setEnabled(True)
        self.table.setGeometry(QtCore.QRect(10, 380, 800, 250))
        self.table.setStyleSheet("background:rgb(225, 225, 225);\n"
"color: rgb(199, 55, 255);\n"
"")
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setShowGrid(True)
        self.table.setGridStyle(QtCore.Qt.DotLine)
        self.table.setWordWrap(True)
        self.table.setRowCount(13)
        self.table.setColumnCount(4)
        self.table.setObjectName("table")
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setKerning(False)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.table.setItem(1, 2, item)
        self.table.horizontalHeader().setVisible(True)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setDefaultSectionSize(90)
        self.table.horizontalHeader().setHighlightSections(False)
        self.table.horizontalHeader().setMinimumSectionSize(50)
        self.table.horizontalHeader().setSortIndicatorShown(True)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setDefaultSectionSize(20)
        self.table.verticalHeader().setHighlightSections(False)
        self.table.verticalHeader().setMinimumSectionSize(20)
        self.table.verticalHeader().setSortIndicatorShown(True)
        self.table.verticalHeader().setStretchLastSection(False)
        self.weight_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.weight_label.setGeometry(QtCore.QRect(10, 650, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.weight_label.setFont(font)
        self.weight_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color:rgb(255, 255, 255);")
        self.weight_label.setObjectName("weight_label")
        self.weight_value = QtWidgets.QLabel(self.bending_price_calc_window)
        self.weight_value.setGeometry(QtCore.QRect(150, 650, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.weight_value.setFont(font)
        self.weight_value.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255)\n"
";")
        self.weight_value.setObjectName("weight_value")
        self.kg_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.kg_label.setGeometry(QtCore.QRect(240, 650, 20, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.kg_label.setFont(font)
        self.kg_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);")
        self.kg_label.setObjectName("kg_label")
        self.lenght_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.lenght_label.setGeometry(QtCore.QRect(10, 680, 350, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.lenght_label.setFont(font)
        self.lenght_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 102, 0);")
        self.lenght_label.setObjectName("lenght_label")
        self.lenght_value = QtWidgets.QLabel(self.bending_price_calc_window)
        self.lenght_value.setGeometry(QtCore.QRect(370, 680, 65, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.lenght_value.setFont(font)
        self.lenght_value.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 102, 0);")
        self.lenght_value.setObjectName("lenght_value")
        self.cm_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.cm_label.setGeometry(QtCore.QRect(440, 680, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.cm_label.setFont(font)
        self.cm_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 102, 0);")
        self.cm_label.setObjectName("cm_label")
        self.xlsx_button = QtWidgets.QPushButton(self.bending_price_calc_window)
        self.xlsx_button.setGeometry(QtCore.QRect(10, 820, 230, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.xlsx_button.setFont(font)
        self.xlsx_button.setStyleSheet("QPushButton {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(84, 198, 11, 255), stop:0.369318 rgba(23, 104, 10, 255), stop:0.98 rgba(13, 212, 2, 255), stop:1 rgba(0, 0, 0, 0));\n"
"color:white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  rgb(48, 221, 255);\n"
"}")
        self.xlsx_button.setObjectName("xlsx_button")
        self.clear_table_button = QtWidgets.QPushButton(self.bending_price_calc_window)
        self.clear_table_button.setGeometry(QtCore.QRect(580, 820, 230, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.clear_table_button.setFont(font)
        self.clear_table_button.setStyleSheet("QPushButton {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(243, 33, 61, 255), stop:0.55 rgba(235, 61, 61, 255), stop:0.98 rgba(134, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"color:white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  rgb(48, 221, 255);\n"
"}")
        self.clear_table_button.setObjectName("clear_table_button")
        self.date_euro_layout = QtWidgets.QWidget(self.bending_price_calc_window)
        self.date_euro_layout.setEnabled(False)
        self.date_euro_layout.setGeometry(QtCore.QRect(570, 20, 240, 171))
        self.date_euro_layout.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(69, 1, 255, 255), stop:0.55 rgba(34, 54, 133, 255), stop:0.98 rgba(2, 34, 212, 255), stop:1 rgba(0, 0, 0, 0));\n"
"border-radius: 10px;")
        self.date_euro_layout.setObjectName("date_euro_layout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.date_euro_layout)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.date_euro_layout)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.title.setFont(font)
        self.title.setToolTipDuration(18)
        self.title.setStyleSheet("QLabel {\n"
"    color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"}")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.date_value = QtWidgets.QLabel(self.date_euro_layout)
        self.date_value.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.date_value.setFont(font)
        self.date_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.date_value.setStyleSheet("QLabel {\n"
"    color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"}")
        self.date_value.setAlignment(QtCore.Qt.AlignCenter)
        self.date_value.setObjectName("date_value")
        self.verticalLayout.addWidget(self.date_value)
        self.time_label = QtWidgets.QLabel(self.date_euro_layout)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"}")
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.verticalLayout.addWidget(self.time_label)
        self.day = QtWidgets.QLabel(self.date_euro_layout)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.day.setFont(font)
        self.day.setStyleSheet("QLabel {\n"
"    color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"}")
        self.day.setAlignment(QtCore.Qt.AlignCenter)
        self.day.setObjectName("day")
        self.verticalLayout.addWidget(self.day)
        self.euro_layout = QtWidgets.QHBoxLayout()
        self.euro_layout.setObjectName("euro_layout")
        self.euro_label = QtWidgets.QLabel(self.date_euro_layout)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.euro_label.setFont(font)
        self.euro_label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"}")
        self.euro_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.euro_label.setObjectName("euro_label")
        self.euro_layout.addWidget(self.euro_label)
        self.euro_value = QtWidgets.QLabel(self.date_euro_layout)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.euro_value.setFont(font)
        self.euro_value.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"}")
        self.euro_value.setAlignment(QtCore.Qt.AlignCenter)
        self.euro_value.setObjectName("euro_value")
        self.euro_layout.addWidget(self.euro_value)
        self.uah_label = QtWidgets.QLabel(self.date_euro_layout)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.uah_label.setFont(font)
        self.uah_label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"}")
        self.uah_label.setObjectName("uah_label")
        self.euro_layout.addWidget(self.uah_label)
        self.verticalLayout.addLayout(self.euro_layout)
        self.submit_euro_button = QtWidgets.QPushButton(self.bending_price_calc_window)
        self.submit_euro_button.setEnabled(True)
        self.submit_euro_button.setGeometry(QtCore.QRect(570, 280, 240, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.submit_euro_button.setFont(font)
        self.submit_euro_button.setStyleSheet("QPushButton {\n"
"background-color:rgb(102, 161, 255);\n"
"color:white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(48, 221, 255);\n"
"}")
        self.submit_euro_button.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.submit_euro_button.setShortcut("")
        self.submit_euro_button.setObjectName("submit_euro_button")
        self.EURO_value = QtWidgets.QLineEdit(self.bending_price_calc_window)
        self.EURO_value.setGeometry(QtCore.QRect(570, 240, 240, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.EURO_value.setFont(font)
        self.EURO_value.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color:rgb(190, 227, 255);\n"
"    color: rgb(202, 8, 255);\n"
"    border: 1px  rgb(237, 255, 152);\n"
"border-radius: 5px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(2, 35, 255);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(0, 255, 162);\n"
"}")
        self.EURO_value.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.EURO_value.setAlignment(QtCore.Qt.AlignCenter)
        self.EURO_value.setObjectName("EURO_value")
        self.refresh_rate_button = QtWidgets.QPushButton(self.bending_price_calc_window)
        self.refresh_rate_button.setEnabled(True)
        self.refresh_rate_button.setGeometry(QtCore.QRect(570, 200, 240, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.refresh_rate_button.setFont(font)
        self.refresh_rate_button.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"background-color: rgb(0, 38, 255);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  rgb(48, 221, 255);\n"
"}")
        self.refresh_rate_button.setObjectName("refresh_rate_button")
        self.comission_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.comission_label.setGeometry(QtCore.QRect(380, 720, 80, 35))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.comission_label.setFont(font)
        self.comission_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 0, 0);")
        self.comission_label.setObjectName("comission_label")
        self.persentage_spinBox = QtWidgets.QSpinBox(self.bending_price_calc_window)
        self.persentage_spinBox.setGeometry(QtCore.QRect(470, 720, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.persentage_spinBox.setFont(font)
        self.persentage_spinBox.setStyleSheet("QSpinBox{\n"
"    background-color:  rgb(190, 227, 255);\n"
"    color:  rgb(0, 0, 100);\n"
"border-radius: 5px;\n"
"}\n"
"QSpinBox:hover {\n"
"    border: 3px solid rgb(2, 35, 255);\n"
"}\n"
"QSpinBox:focus {\n"
"\n"
"    border: 3px solid rgb(225, 255, 249);\n"
"}\n"
"QSpinBox::up-arrow {\n"
"color : blue;\n"
"}\n"
"QSpinBox::down-arrow {\n"
"color : red;\n"
"}\n"
"")
        self.persentage_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.persentage_spinBox.setProperty("value", 15)
        self.persentage_spinBox.setObjectName("persentage_spinBox")
        self.percent_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.percent_label.setGeometry(QtCore.QRect(530, 720, 20, 35))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.percent_label.setFont(font)
        self.percent_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 0, 0);")
        self.percent_label.setObjectName("percent_label")
        self.kp_button = QtWidgets.QPushButton(self.bending_price_calc_window)
        self.kp_button.setGeometry(QtCore.QRect(290, 820, 230, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.kp_button.setFont(font)
        self.kp_button.setStyleSheet("QPushButton {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(84, 198, 11, 255), stop:0.369318 rgba(23, 104, 10, 255), stop:0.98 rgba(13, 212, 2, 255), stop:1 rgba(0, 0, 0, 0));\n"
"color:white;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  rgb(48, 221, 255);\n"
"}")
        self.kp_button.setObjectName("kp_button")
        self.search_button = QtWidgets.QPushButton(self.bending_price_calc_window)
        self.search_button.setGeometry(QtCore.QRect(10, 330, 800, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.search_button.setFont(font)
        self.search_button.setStyleSheet("QPushButton {\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(57, 213, 219, 255), stop:0.5625 rgba(17, 134, 158, 255), stop:0.98 rgba(4, 172, 196, 255), stop:1 rgba(0, 0, 0, 0));\n"
"color:white;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  rgb(48, 221, 255);\n"
"}")
        self.search_button.setObjectName("search_button")
        self.packing_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.packing_label.setGeometry(QtCore.QRect(10, 720, 180, 35))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.packing_label.setFont(font)
        self.packing_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 0, 0);")
        self.packing_label.setObjectName("packing_label")
        self.delivery_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.delivery_label.setGeometry(QtCore.QRect(10, 760, 180, 35))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.delivery_label.setFont(font)
        self.delivery_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 0, 0);")
        self.delivery_label.setObjectName("delivery_label")
        self.packing_value = QtWidgets.QLineEdit(self.bending_price_calc_window)
        self.packing_value.setGeometry(QtCore.QRect(200, 720, 85, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.packing_value.setFont(font)
        self.packing_value.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color:  rgb(190, 227, 255);\n"
"    color:  rgb(0, 0, 100);\n"
"    border: 1px  rgb(237, 255, 152);\n"
"border-radius: 5px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(2, 35, 255);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(0, 255, 162);\n"
"}")
        self.packing_value.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.packing_value.setAlignment(QtCore.Qt.AlignCenter)
        self.packing_value.setObjectName("packing_value")
        self.delivery_value = QtWidgets.QLineEdit(self.bending_price_calc_window)
        self.delivery_value.setGeometry(QtCore.QRect(200, 760, 85, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.delivery_value.setFont(font)
        self.delivery_value.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color:  rgb(190, 227, 255);\n"
"    color: rgb(202, 8, 255);\n"
"    border: 1px  rgb(237, 255, 152);\n"
"border-radius: 5px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(2, 35, 255);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(0, 255, 162);\n"
"}")
        self.delivery_value.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.delivery_value.setAlignment(QtCore.Qt.AlignCenter)
        self.delivery_value.setObjectName("delivery_value")
        self.packing_euro_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.packing_euro_label.setGeometry(QtCore.QRect(290, 720, 60, 35))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.packing_euro_label.setFont(font)
        self.packing_euro_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 0, 0);")
        self.packing_euro_label.setObjectName("packing_euro_label")
        self.delivery_euro_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.delivery_euro_label.setGeometry(QtCore.QRect(290, 760, 60, 35))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.delivery_euro_label.setFont(font)
        self.delivery_euro_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 0, 0);")
        self.delivery_euro_label.setObjectName("delivery_euro_label")
        self.discount_spinBox = QtWidgets.QSpinBox(self.bending_price_calc_window)
        self.discount_spinBox.setGeometry(QtCore.QRect(470, 760, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.discount_spinBox.setFont(font)
        self.discount_spinBox.setStyleSheet("QSpinBox{\n"
"    background-color:  rgb(190, 227, 255);\n"
"    color:  rgb(0, 0, 100);\n"
"border-radius: 5px;\n"
"}\n"
"QSpinBox:hover {\n"
"    border: 3px solid rgb(2, 35, 255);\n"
"}\n"
"QSpinBox:focus {\n"
"\n"
"    border: 3px solid rgb(225, 255, 249);\n"
"}\n"
"QSpinBox::up-arrow {\n"
"color : blue;\n"
"}\n"
"QSpinBox::down-arrow {\n"
"color : red;\n"
"}\n"
"")
        self.discount_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.discount_spinBox.setProperty("value", 15)
        self.discount_spinBox.setObjectName("discount_spinBox")
        self.discount_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.discount_label.setGeometry(QtCore.QRect(380, 760, 80, 35))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.discount_label.setFont(font)
        self.discount_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 253, 240);")
        self.discount_label.setObjectName("discount_label")
        self.percent_discount_label = QtWidgets.QLabel(self.bending_price_calc_window)
        self.percent_discount_label.setGeometry(QtCore.QRect(530, 760, 20, 35))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.percent_discount_label.setFont(font)
        self.percent_discount_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 253, 240);")
        self.percent_discount_label.setObjectName("percent_discount_label")
        self.add_amount_button = QtWidgets.QPushButton(self.bending_price_calc_window)
        self.add_amount_button.setGeometry(QtCore.QRect(490, 640, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.add_amount_button.setFont(font)
        self.add_amount_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_amount_button.setStyleSheet("\n"
"QPushButton {\n"
"background: rgb(102, 161, 255);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(48, 221, 255);\n"
"}")
        self.add_amount_button.setObjectName("add_amount_button")
        self.remove_amount_button = QtWidgets.QPushButton(self.bending_price_calc_window)
        self.remove_amount_button.setGeometry(QtCore.QRect(600, 640, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.remove_amount_button.setFont(font)
        self.remove_amount_button.setStyleSheet("\n"
"QPushButton{\n"
"background: rgb(25, 153, 117);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(48, 221, 255);\n"
"}")
        self.remove_amount_button.setObjectName("remove_amount_button")
        self.remove_amount_button_2 = QtWidgets.QPushButton(self.bending_price_calc_window)
        self.remove_amount_button_2.setGeometry(QtCore.QRect(710, 640, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.remove_amount_button_2.setFont(font)
        self.remove_amount_button_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.remove_amount_button_2.setStyleSheet("\n"
"QPushButton {\n"
"background: red;\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(48, 221, 255);\n"
"}")
        self.remove_amount_button_2.setObjectName("remove_amount_button_2")
        self.db_button = QtWidgets.QPushButton(self.bending_price_calc_window)
        self.db_button.setGeometry(QtCore.QRect(599, 700, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.db_button.setFont(font)
        self.db_button.setStyleSheet("QPushButton {\n"
"color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(88, 45, 175, 255), stop:0.369318 rgba(70, 88, 170, 255), stop:0.98 rgba(11, 121, 238, 255), stop:1 rgba(0, 0, 0, 0));\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:  rgb(48, 221, 255);\n"
"}")
        self.db_button.setObjectName("db_button")
        MainWindow.setCentralWidget(self.bending_price_calc_window)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #Власний код
        for item_connection in type_holder_list:
            self.type_value.addItem(item_connection)
        self.type_value.setStyleSheet(
                "QComboBox{\n"
                "    background-color:rgb(190, 227, 255);\n"                
                #"    background-color:red;\n"
                "    color:  rgb(0, 0, 100);\n"
                "    border: 1px  rgb(237, 255, 152);\n"
                "    border-radius: 5px;\n"
                "}\n"
                "QListWidget::item{\n"
                "    background-color: rgb(111, 247, 125);\n"
                "    color: red;\n"
                "}\n"
                # "QListView{\n"
                # "    background-color: yellow;"
                # "    color:  rgb(0, 0, 100);\n"
                # "}\n"
                "QScrollBar{\n"
                "    background-color:rgb(190, 227, 255);\n"
                "}\n"
                "QComboBox:hover {\n"
                "    border: 3px solid rgb(2, 35, 255);\n"
                "}\n"
                "QComboBox:focus {\n"
                "\n"
                "    border: 3px solid rgb(0, 255, 162);\n"
                "}\n"
                "QScrollBar {\n"
                "    background-color: rgb(237, 255, 152);\n"
                "    color: yellow;\n"
                "}\n"
                "QScrollBar::handle::pressed {\n"
                "    background : lightgreen;\n"
                "}"

        )


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.company_label.setText(_translate("MainWindow", "Компанія"))
        self.company_name.setText(_translate("MainWindow", "Vectortool"))
        self.type_label.setText(_translate("MainWindow", "Tип"))
        self.item_label.setText(_translate("MainWindow", "Виріб"))
        self.item_value.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>QComboBox{</p><p>    background-color: rgb(237, 255, 152);</p><p>    color: rgb(202, 8, 255);</p><p>}</p><p>QComboBoxt:hover {</p><p>    border: 3px solid rgb(2, 35, 255);</p><p>}</p><p>QComboBox:focus {</p><p><br/></p><p>    border: 3px solid rgb(225, 255, 249);</p><p>}</p></body></html>"))
        self.number_label.setText(_translate("MainWindow", "Номер"))
        self.length_label.setText(_translate("MainWindow", "Довжина"))
        self.quantity_label.setText(_translate("MainWindow", "Кількість"))
        self.add_item_button.setText(_translate("MainWindow", "Додати виріб"))
        self.reset_button.setText(_translate("MainWindow", "Все с початку"))
        self.table.setSortingEnabled(True)
        item = self.table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.table.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.table.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.table.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.table.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "13"))
        item = self.table.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "14"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "№"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Код"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Кількість"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Назва"))
        __sortingEnabled = self.table.isSortingEnabled()
        self.table.setSortingEnabled(False)
        item = self.table.item(1, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.table.item(1, 1)
        item.setText(_translate("MainWindow", "23.654"))
        item = self.table.item(1, 2)
        item.setText(_translate("MainWindow", "gfdsfgssddsfghgdfssghdgfs1234567890"))
        self.table.setSortingEnabled(__sortingEnabled)
        self.weight_label.setText(_translate("MainWindow", "Вага складає"))
        self.weight_value.setText(_translate("MainWindow", "0000.00"))
        self.kg_label.setText(_translate("MainWindow", "кг"))
        self.lenght_label.setText(_translate("MainWindow", "Максимальна довжина одного виробу"))
        self.lenght_value.setText(_translate("MainWindow", "000.00"))
        self.cm_label.setText(_translate("MainWindow", "см"))
        self.xlsx_button.setText(_translate("MainWindow", "Створити xlsx"))
        self.clear_table_button.setText(_translate("MainWindow", "Скинути таблицю"))
        self.title.setText(_translate("MainWindow", "Курс по міжбанку станом на"))
        self.date_value.setText(_translate("MainWindow", "26.07.2023"))
        self.time_label.setText(_translate("MainWindow", "11:22"))
        self.day.setText(_translate("MainWindow", "Середа"))
        self.euro_label.setText(_translate("MainWindow", "EUR"))
        self.euro_value.setText(_translate("MainWindow", "00,0000"))
        self.uah_label.setText(_translate("MainWindow", "ГРН"))
        self.submit_euro_button.setText(_translate("MainWindow", "Застосувати курс"))
        self.refresh_rate_button.setText(_translate("MainWindow", "Оновити"))
        self.comission_label.setText(_translate("MainWindow", "Комісія"))
        self.percent_label.setText(_translate("MainWindow", "%"))
        self.kp_button.setText(_translate("MainWindow", "Створити КП xlsx"))
        self.search_button.setText(_translate("MainWindow", "Підібрати пуансон або матрицю"))
        self.packing_label.setText(_translate("MainWindow", "Вартість пакування"))
        self.delivery_label.setText(_translate("MainWindow", "Вартість доставки"))
        self.packing_euro_label.setText(_translate("MainWindow", "EURO"))
        self.delivery_euro_label.setText(_translate("MainWindow", "EURO"))
        self.discount_label.setText(_translate("MainWindow", "Знижка"))
        self.percent_discount_label.setText(_translate("MainWindow", "%"))
        self.add_amount_button.setText(_translate("MainWindow", "+1"))
        self.remove_amount_button.setText(_translate("MainWindow", "-1"))
        self.remove_amount_button_2.setText(_translate("MainWindow", "Видалити"))
        self.db_button.setText(_translate("MainWindow", "База"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
